version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
